[project]
name = "bot-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "huggingface-hub>=0.36.0",
    "telegram>=0.0.1",
    "transformers>=4.40.0",
]
